### ISSUE TITLE
代码在373行存在错误？

### ISSUE THREAD

**Issue by ShuGuoJ** [jjwwczy/jjwwczy-SiameseNet-for-few-shot-Hyperspectral-Classification#4]
![image](https://user-images.githubusercontent.com/39252475/113264714-dace3a00-9305-11eb-867b-fb4efd4460d5.png)
划线部分是否应该改为`r-margin:r+marigin+1`？若按照原始代码的中的写法，程序一直在生成以原始图像第一列像素为中心像素点的patch。

**Comment by jjwwczy** [comment]
恩是的，这是之前很早的版本，我改了以后忘了更新了。现在已上传最新的版本。
